# Generated by Django 6.0 on 2025-12-21 09:55
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagequeue',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.appointment'),
        ),
    ]
